# Generated by Django 2.2.2 on 2019-10-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerinfo',
            name='gateway_iothost',
            field=models.CharField(default='', max_length=30, verbose_name='ip地址'),
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='gateway_iotid',
            field=models.CharField(default='', max_length=30, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='gateway_iotport',
            field=models.CharField(default='', max_length=30, verbose_name='端口'),
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='gateway_iottoken',
            field=models.CharField(default='', max_length=30, verbose_name='密码'),
        ),
    ]
