# Generated by Django 2.2.6 on 2019-10-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('drive_name', models.CharField(max_length=30, verbose_name='驱动名称')),
                ('drive_path', models.CharField(max_length=150, verbose_name='驱动路径')),
                ('drive_remark', models.CharField(max_length=150, verbose_name='驱动描述')),
            ],
            options={
                'verbose_name_plural': '网关子设备列表信息',
                'db_table': 'gateway_drive_list',
                'verbose_name': '网关子设备列表信息',
            },
        ),
    ]
