# Generated by Django 2.2.6 on 2019-10-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='drive_type',
            field=models.CharField(default='dsds', max_length=30, verbose_name='驱动类型'),
            preserve_default=False,
        ),
    ]
